"""Prompt modules for ChemQA."""

from prompts.core import (
    CLAIM_MINER_SYSTEM_PROMPT,
    ENTITY_MENTION_EXTRACTION_SYSTEM_PROMPT,
    ENTITY_RESOLVER_SYSTEM_PROMPT,
    EVIDENCE_EXTRACTOR_SYSTEM_PROMPT,
    QUERY_PLANNER_SYSTEM_PROMPT,
    ROUTER_LOCALIZATION_SYSTEM_PROMPT,
    ROUTER_SEMANTIC_SYSTEM_PROMPT,
    ROUTER_SYSTEM_PROMPT,
    build_claim_miner_user_prompt,
    build_entity_mention_extraction_user_prompt,
    build_entity_resolver_user_prompt,
    build_evidence_extractor_user_prompt,
    build_query_planner_user_prompt,
    build_router_localization_user_prompt,
    build_router_semantic_user_prompt,
)
from prompts.react_reviewed import (
    build_proposer_action_prompt,
    build_proposer_repair_system_prompt,
    build_proposer_system_prompt,
    build_proposer_thought_prompt,
    build_proposer_user_prompt,
    build_review_prompt_contract,
    build_reviewer_action_prompt,
    build_reviewer_repair_system_prompt,
    build_reviewer_system_prompt,
    build_reviewer_thought_prompt,
    build_reviewer_user_prompt,
    build_screening_system_prompt,
    build_submission_prompt_contract,
    build_submission_prompt_scaffold,
)

__all__ = [
    "CLAIM_MINER_SYSTEM_PROMPT",
    "ENTITY_MENTION_EXTRACTION_SYSTEM_PROMPT",
    "ENTITY_RESOLVER_SYSTEM_PROMPT",
    "EVIDENCE_EXTRACTOR_SYSTEM_PROMPT",
    "QUERY_PLANNER_SYSTEM_PROMPT",
    "ROUTER_SEMANTIC_SYSTEM_PROMPT",
    "ROUTER_LOCALIZATION_SYSTEM_PROMPT",
    "ROUTER_SYSTEM_PROMPT",
    "build_claim_miner_user_prompt",
    "build_entity_mention_extraction_user_prompt",
    "build_entity_resolver_user_prompt",
    "build_evidence_extractor_user_prompt",
    "build_query_planner_user_prompt",
    "build_router_semantic_user_prompt",
    "build_router_localization_user_prompt",
    "build_proposer_action_prompt",
    "build_proposer_repair_system_prompt",
    "build_proposer_system_prompt",
    "build_proposer_thought_prompt",
    "build_proposer_user_prompt",
    "build_review_prompt_contract",
    "build_reviewer_action_prompt",
    "build_reviewer_repair_system_prompt",
    "build_reviewer_system_prompt",
    "build_reviewer_thought_prompt",
    "build_reviewer_user_prompt",
    "build_screening_system_prompt",
    "build_submission_prompt_contract",
    "build_submission_prompt_scaffold",
]
