"""Prompt modules for centralized prompt management."""

from prompts.system_prompts import UNIFIED_SYSTEM_PROMPT
from prompts.debate_phase_prompts import (
    DEBATE_PROPOSE_SYSTEM_PROMPT,
    DEBATE_REVIEW_SYSTEM_PROMPT,
    DEBATE_REBUTTAL_SYSTEM_PROMPT,
    build_initial_debate_prompt,
)
from prompts.qa_prompts import (
    CLAIM_MINER_SYSTEM_PROMPT,
    CLAIM_REVISION_SYSTEM_PROMPT,
    CITATION_REVIEWER_SYSTEM_PROMPT,
    CONTRADICTION_REVIEWER_SYSTEM_PROMPT,
    ENTITY_RESOLVER_SYSTEM_PROMPT,
    EVIDENCE_EXTRACTOR_SYSTEM_PROMPT,
    METHODOLOGY_REVIEWER_SYSTEM_PROMPT,
    QUERY_PLANNER_SYSTEM_PROMPT,
    REVIEW_MERGE_SYSTEM_PROMPT,
    ROUTER_SYSTEM_PROMPT,
    SYNTHESIS_SYSTEM_PROMPT,
    build_claim_miner_user_prompt,
    build_claim_revision_user_prompt,
    build_contradiction_reviewer_user_prompt,
    build_entity_resolver_user_prompt,
    build_evidence_extractor_user_prompt,
    build_query_planner_user_prompt,
    build_reviewer_user_prompt,
    build_review_merge_user_prompt,
    build_router_user_prompt,
    build_synthesizer_user_prompt,
)

__all__ = [
    "UNIFIED_SYSTEM_PROMPT",
    "DEBATE_PROPOSE_SYSTEM_PROMPT",
    "build_initial_debate_prompt",
    "DEBATE_REVIEW_SYSTEM_PROMPT",
    "DEBATE_REBUTTAL_SYSTEM_PROMPT",
    "ENTITY_RESOLVER_SYSTEM_PROMPT",
    "QUERY_PLANNER_SYSTEM_PROMPT",
    "EVIDENCE_EXTRACTOR_SYSTEM_PROMPT",
    "CLAIM_MINER_SYSTEM_PROMPT",
    "METHODOLOGY_REVIEWER_SYSTEM_PROMPT",
    "CITATION_REVIEWER_SYSTEM_PROMPT",
    "CONTRADICTION_REVIEWER_SYSTEM_PROMPT",
    "CLAIM_REVISION_SYSTEM_PROMPT",
    "REVIEW_MERGE_SYSTEM_PROMPT",
    "ROUTER_SYSTEM_PROMPT",
    "SYNTHESIS_SYSTEM_PROMPT",
    "build_entity_resolver_user_prompt",
    "build_query_planner_user_prompt",
    "build_evidence_extractor_user_prompt",
    "build_claim_miner_user_prompt",
    "build_reviewer_user_prompt",
    "build_contradiction_reviewer_user_prompt",
    "build_claim_revision_user_prompt",
    "build_review_merge_user_prompt",
    "build_router_user_prompt",
    "build_synthesizer_user_prompt",
]
